# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""NeMo Gym resources server for multi-turn local AI search."""

import json
import re
import string
import unicodedata
from collections import Counter
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

from fastapi import FastAPI, Request
from pydantic import BaseModel, Field, PrivateAttr

from nemo_gym.base_resources_server import (
    BaseResourcesServerConfig,
    BaseRunRequest,
    BaseSeedSessionRequest,
    BaseSeedSessionResponse,
    BaseVerifyRequest,
    BaseVerifyResponse,
    SimpleResourcesServer,
)
from nemo_gym.openai_utils import NeMoGymResponse, NeMoGymResponseOutputMessage
from nemo_gym.server_utils import SESSION_ID_KEY
from resources_servers.ai_search.retrieval.batching import AsyncSearchBatcher
from resources_servers.ai_search.retrieval.config import SearchRuntimeConfig
from resources_servers.ai_search.retrieval.engine import DenseSearchEngine
from resources_servers.ai_search.retrieval.http import HttpSearchProvider
from resources_servers.ai_search.observability import trace_span
from resources_servers.ai_search.prometheus import SearchPrometheusMetrics
from resources_servers.ai_search.retrieval.types import SearchProvider


_FINAL_ANSWER_PATTERN = re.compile(
    r"^\s*Final Answer\s*:\s*(.+?)\s*$", flags=re.IGNORECASE | re.MULTILINE
)
_ANSWER_TAG_PATTERN = re.compile(
    r"<answer>\s*(.*?)\s*</answer>", flags=re.IGNORECASE | re.DOTALL
)
_SEARCH_R1_ANSWER_PATTERN = re.compile(r"<answer>(.*?)</answer>", flags=re.DOTALL)
_ARTICLES_PATTERN = re.compile(r"\b(a|an|the)\b", flags=re.IGNORECASE)


class AISearchResourcesServerConfig(BaseResourcesServerConfig):
    """Configuration injected into the AI-search resources server."""

    search: SearchRuntimeConfig


class SearchRequest(BaseModel):
    """Arguments generated by the policy for one local search call."""

    query: str = Field(
        min_length=1,
        max_length=4096,
        description="A concise natural-language query for the local document index.",
    )
    top_k: int | None = Field(
        default=None,
        ge=1,
        description="Optional number of documents to return.",
    )


class SearchDocumentResponse(BaseModel):
    """One document exposed to the policy as tool output."""

    rank: int
    doc_id: str
    title: str
    text: str
    score: float | None


class SearchResponse(BaseModel):
    """Structured local-search response consumed by the policy."""

    query: str
    results: list[SearchDocumentResponse]
    error: str | None = None


class AISearchRunRequest(BaseRunRequest):
    """Dataset fields used during rollout and verification."""

    question: str
    answers: list[str] = Field(min_length=1)
    supporting_doc_ids: list[str] = Field(default_factory=list)
    source_id: str | None = None
    data_source: str | None = None


class AISearchVerifyRequest(AISearchRunRequest, BaseVerifyRequest):
    """Completed rollout plus its expected answer metadata."""


class AISearchVerifyResponse(AISearchVerifyRequest, BaseVerifyResponse):
    """Scalar reward, decomposed reward, and search-quality diagnostics."""

    reward_components: dict[str, float]
    parsed_answer: str
    answer_f1: float
    exact_match: float
    retrieval_recall: float
    format_valid: float
    search_efficiency: float
    num_search_calls: int
    duplicate_query_rate: float
    search_error_count: int
    retrieved_doc_ids: list[str]
    mean_queue_ms: float
    mean_encode_ms: float
    mean_index_ms: float
    mean_fetch_ms: float
    mean_search_total_ms: float
    query_cache_hit_rate: float


class _SearchCallMetrics(BaseModel):
    query: str
    retrieved_doc_ids: list[str]
    queue_ms: float
    encode_ms: float
    index_ms: float
    fetch_ms: float
    total_ms: float
    cache_hits: int
    cache_misses: int


class _SessionMetrics(BaseModel):
    calls: list[_SearchCallMetrics] = Field(default_factory=list)
    errors: int = 0


def _normalize_answer(text: str) -> str:
    """SQuAD-style normalization without assuming ASCII-only punctuation."""
    casefolded = text.casefold()
    no_punctuation = "".join(
        " " if unicodedata.category(character).startswith("P") else character
        for character in casefolded
    )
    no_articles = _ARTICLES_PATTERN.sub(" ", no_punctuation)
    return " ".join(no_articles.split())


def _normalize_search_r1_answer(text: str) -> str:
    """Match Search-R1's ASCII-punctuation exact-match normalization."""
    lowered = text.lower()
    no_punctuation = "".join(
        character for character in lowered if character not in string.punctuation
    )
    no_articles = _ARTICLES_PATTERN.sub(" ", no_punctuation)
    return " ".join(no_articles.split())


def _token_f1(prediction: str, reference: str) -> float:
    prediction_tokens = _normalize_answer(prediction).split()
    reference_tokens = _normalize_answer(reference).split()
    if not prediction_tokens or not reference_tokens:
        return float(prediction_tokens == reference_tokens)
    common = Counter(prediction_tokens) & Counter(reference_tokens)
    overlap = sum(common.values())
    if overlap == 0:
        return 0.0
    precision = overlap / len(prediction_tokens)
    recall = overlap / len(reference_tokens)
    return 2.0 * precision * recall / (precision + recall)


def _parse_final_answer(output_text: str) -> tuple[str, bool]:
    """Extract the final answer while separately reporting format validity."""
    formatted_matches = _FINAL_ANSWER_PATTERN.findall(output_text)
    if formatted_matches:
        return formatted_matches[-1].strip(), True

    tag_matches = _ANSWER_TAG_PATTERN.findall(output_text)
    if tag_matches:
        return tag_matches[-1].strip(), False

    stripped = output_text.strip()
    try:
        parsed = json.loads(stripped)
    except json.JSONDecodeError:
        return stripped, False
    if isinstance(parsed, dict) and isinstance(parsed.get("answer"), str):
        return parsed["answer"].strip(), False
    return stripped, False


def _parse_search_r1_answer(output_text: str) -> tuple[str, bool]:
    """Extract the last case-sensitive answer tag emitted by the policy."""
    matches = _SEARCH_R1_ANSWER_PATTERN.findall(output_text)
    if not matches:
        return "", False
    return matches[-1].strip(), True


def _response_assistant_text(response: NeMoGymResponse) -> str:
    """Read assistant text while ignoring interleaved user observations."""
    chunks: list[str] = []
    for item in response.output:
        if not isinstance(item, NeMoGymResponseOutputMessage):
            continue
        for content in item.content:
            text = getattr(content, "text", None)
            if isinstance(text, str):
                chunks.append(text)
    return "".join(chunks)


def _mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0.0


class AISearchResourcesServer(SimpleResourcesServer):
    """Owns the local retriever, search tools, session state, and verifier."""

    config: AISearchResourcesServerConfig

    _provider: SearchProvider = PrivateAttr()
    _batcher: AsyncSearchBatcher = PrivateAttr()
    _session_metrics: dict[str, _SessionMetrics] = PrivateAttr(default_factory=dict)
    _prometheus: SearchPrometheusMetrics = PrivateAttr()

    def model_post_init(self, __context: Any) -> None:
        super().model_post_init(__context)
        server_dir = Path(__file__).resolve().parent
        runtime_config = self.config.search.model_copy(deep=True)
        runtime_config.corpus_path = self._resolve_path(
            runtime_config.corpus_path, server_dir
        )
        runtime_config.embeddings_path = self._resolve_path(
            runtime_config.embeddings_path, server_dir
        )
        if runtime_config.index.serialized_index_path is not None:
            runtime_config.index.serialized_index_path = self._resolve_path(
                runtime_config.index.serialized_index_path, server_dir
            )

        self._provider = self._build_search_provider(runtime_config)
        self._prometheus = SearchPrometheusMetrics(runtime_config.provider)
        self._batcher = AsyncSearchBatcher(
            provider=self._provider,
            max_batch_size=runtime_config.batch_max_size,
            wait_ms=runtime_config.batch_wait_ms,
            on_queue_depth=self._prometheus.queue_depth.set,
            on_active_batch_size=self._prometheus.observe_active_batch_size,
        )
        if isinstance(self._provider, DenseSearchEngine):
            stats = self._provider.stats
            print(
                "AI-search index ready: "
                f"documents={stats.documents}, dimension={stats.dimension}, "
                f"backend={stats.index_kind}/{stats.index_algorithm}, "
                f"build_or_load_ms={stats.index_build_ms:.2f}"
            )

    @staticmethod
    def _build_search_provider(config: SearchRuntimeConfig) -> SearchProvider:
        """Build the default provider; subclasses can inject an inverted index."""
        if config.provider == "http":
            return HttpSearchProvider(config)
        return DenseSearchEngine(config)

    @staticmethod
    def _resolve_path(path: Path, base_dir: Path) -> Path:
        return path if path.is_absolute() else (base_dir / path).resolve()

    def setup_webserver(self) -> FastAPI:
        app = super().setup_webserver()
        app.post("/search")(self.search)
        app.mount("/metrics", self._prometheus.asgi_app())

        parent_lifespan = app.router.lifespan_context

        @asynccontextmanager
        async def lifespan(app_instance: FastAPI):
            await self._batcher.start()
            try:
                async with parent_lifespan(app_instance) as maybe_state:
                    yield maybe_state
            finally:
                await self._batcher.close()
                self._provider.close()

        app.router.lifespan_context = lifespan
        return app

    async def seed_session(
        self, request: Request, body: BaseSeedSessionRequest
    ) -> BaseSeedSessionResponse:
        del body
        self._session_metrics[request.session[SESSION_ID_KEY]] = _SessionMetrics()
        self._prometheus.active_sessions.set(len(self._session_metrics))
        return BaseSeedSessionResponse()

    async def search(self, request: Request, body: SearchRequest) -> SearchResponse:
        session_id = request.session[SESSION_ID_KEY]
        metrics = self._session_metrics.setdefault(session_id, _SessionMetrics())
        runtime = self.config.search
        with trace_span(
            trace_id=str(session_id),
            component="resource_server",
            operation="search",
            attributes={
                "call_index": len(metrics.calls),
                "provider": runtime.provider,
                "query_chars": len(body.query),
            },
        ) as span:
            self._prometheus.inflight.inc()
            try:
                if len(metrics.calls) >= runtime.max_search_calls:
                    metrics.errors += 1
                    self._prometheus.observe_rejection("budget_exhausted")
                    span.set_attributes(outcome="rejected", reason="budget_exhausted")
                    return SearchResponse(
                        query=body.query,
                        results=[],
                        error=(
                            "Search budget exhausted: at most "
                            f"{runtime.max_search_calls} calls are allowed. "
                            "Give the best final answer now."
                        ),
                    )
                if len(body.query) > runtime.max_query_chars:
                    metrics.errors += 1
                    self._prometheus.observe_rejection("query_too_long")
                    span.set_attributes(outcome="rejected", reason="query_too_long")
                    return SearchResponse(
                        query=body.query,
                        results=[],
                        error=(
                            f"Query is too long ({len(body.query)} characters); "
                            f"maximum is {runtime.max_query_chars}."
                        ),
                    )

                top_k = body.top_k if body.top_k is not None else runtime.default_top_k
                if top_k > runtime.max_top_k:
                    metrics.errors += 1
                    self._prometheus.observe_rejection("top_k_too_large")
                    span.set_attributes(
                        outcome="rejected", reason="top_k_too_large", top_k=top_k
                    )
                    return SearchResponse(
                        query=body.query,
                        results=[],
                        error=f"top_k cannot exceed {runtime.max_top_k}",
                    )

                try:
                    result = await self._batcher.search(body.query, top_k)
                except Exception:
                    self._prometheus.observe_provider_error()
                    raise
                timings = result.timings
                self._prometheus.observe_success(timings)
                span.set_attributes(
                    outcome="success",
                    top_k=top_k,
                    hits=len(result.hits),
                    batch_size=timings.batch_size,
                    queue_ms=timings.queue_ms,
                    encode_ms=timings.encode_ms,
                    index_ms=timings.index_ms,
                    fetch_ms=timings.fetch_ms,
                    provider_total_ms=timings.total_ms,
                    provider_batch_id=timings.provider_batch_id,
                )
                metrics.calls.append(
                    _SearchCallMetrics(
                        query=body.query,
                        retrieved_doc_ids=[hit.document.id for hit in result.hits],
                        queue_ms=timings.queue_ms,
                        encode_ms=timings.encode_ms,
                        index_ms=timings.index_ms,
                        fetch_ms=timings.fetch_ms,
                        total_ms=timings.total_ms,
                        cache_hits=timings.cache_hits,
                        cache_misses=timings.cache_misses,
                    )
                )
                return SearchResponse(
                    query=body.query,
                    results=[
                        SearchDocumentResponse(
                            rank=hit.rank,
                            doc_id=hit.document.id,
                            title=hit.document.title,
                            text=hit.document.text,
                            score=hit.score if runtime.include_scores else None,
                        )
                        for hit in result.hits
                    ],
                )
            finally:
                self._prometheus.inflight.dec()

    async def verify(
        self, request: Request, body: AISearchVerifyRequest
    ) -> AISearchVerifyResponse:
        session_id = request.session[SESSION_ID_KEY]
        metrics = self._session_metrics.pop(session_id, _SessionMetrics())
        self._prometheus.active_sessions.set(len(self._session_metrics))
        self._prometheus.search_calls_per_session.observe(len(metrics.calls))

        output_text = _response_assistant_text(body.response)
        reward_config = self.config.search.reward
        if reward_config.answer_metric == "search_r1_exact_match":
            parsed_answer, format_valid_bool = _parse_search_r1_answer(output_text)
            normalize_for_exact_match = _normalize_search_r1_answer
        else:
            parsed_answer, format_valid_bool = _parse_final_answer(output_text)
            normalize_for_exact_match = _normalize_answer
        answer_f1 = max(_token_f1(parsed_answer, answer) for answer in body.answers)
        exact_match = float(
            any(
                normalize_for_exact_match(parsed_answer)
                == normalize_for_exact_match(answer)
                for answer in body.answers
            )
        )
        answer_score = (
            exact_match
            if reward_config.answer_metric in ("exact_match", "search_r1_exact_match")
            else answer_f1
        )

        retrieved_doc_ids = list(
            dict.fromkeys(
                doc_id for call in metrics.calls for doc_id in call.retrieved_doc_ids
            )
        )
        expected_support = set(body.supporting_doc_ids)
        retrieval_recall = (
            len(expected_support.intersection(retrieved_doc_ids))
            / len(expected_support)
            if expected_support
            else 0.0
        )
        num_search_calls = len(metrics.calls)
        duplicate_query_rate = (
            1.0
            - len({call.query.casefold().strip() for call in metrics.calls})
            / num_search_calls
            if num_search_calls
            else 0.0
        )
        useful_call_budget = max(1, len(expected_support))
        search_efficiency = 0.0
        if (
            answer_score >= reward_config.answer_threshold_for_efficiency
            and num_search_calls > 0
        ):
            search_efficiency = min(1.0, useful_call_budget / num_search_calls)

        format_valid = float(format_valid_bool and bool(parsed_answer))
        reward_components = {
            "answer": reward_config.answer_weight * answer_score,
            "efficiency": reward_config.efficiency_weight * search_efficiency,
            "format": reward_config.format_weight * format_valid,
            "retrieval": reward_config.retrieval_weight * retrieval_recall,
        }
        cache_hits = sum(call.cache_hits for call in metrics.calls)
        cache_lookups = cache_hits + sum(call.cache_misses for call in metrics.calls)

        return AISearchVerifyResponse(
            **body.model_dump(),
            reward=sum(reward_components.values()),
            reward_components=reward_components,
            parsed_answer=parsed_answer,
            answer_f1=answer_f1,
            exact_match=exact_match,
            retrieval_recall=retrieval_recall,
            format_valid=format_valid,
            search_efficiency=search_efficiency,
            num_search_calls=num_search_calls,
            duplicate_query_rate=duplicate_query_rate,
            search_error_count=metrics.errors,
            retrieved_doc_ids=retrieved_doc_ids,
            mean_queue_ms=_mean([call.queue_ms for call in metrics.calls]),
            mean_encode_ms=_mean([call.encode_ms for call in metrics.calls]),
            mean_index_ms=_mean([call.index_ms for call in metrics.calls]),
            mean_fetch_ms=_mean([call.fetch_ms for call in metrics.calls]),
            mean_search_total_ms=_mean([call.total_ms for call in metrics.calls]),
            query_cache_hit_rate=(cache_hits / cache_lookups if cache_lookups else 0.0),
        )


if __name__ == "__main__":
    AISearchResourcesServer.run_webserver()
